import type { Device } from "@/types/device";
import { DeviceType } from "@/types/device";
import type { Room } from "@/types/room";

export const MOCK_DEVICES: Device[] = [
  {
    id: "light-sala-1",
    name: "Luz Principal",
    type: DeviceType.LIGHT,
    state: "on",
    roomId: "sala",
    attributes: { brightness: 80 },
    online: true,
    lastUpdated: new Date().toISOString(),
    platform: "tuya",
  },
  {
    id: "light-sala-2",
    name: "Abajur Sala",
    type: DeviceType.LIGHT,
    state: "on",
    roomId: "sala",
    attributes: { brightness: 45 },
    online: true,
    lastUpdated: new Date().toISOString(),
    platform: "hue",
  },
  {
    id: "light-quarto-1",
    name: "Luz do Quarto",
    type: DeviceType.LIGHT,
    state: "off",
    roomId: "quarto",
    attributes: { brightness: 60 },
    online: true,
    lastUpdated: new Date().toISOString(),
    platform: "tuya",
  },
  {
    id: "light-cozinha-1",
    name: "Luz Cozinha",
    type: DeviceType.LIGHT,
    state: "on",
    roomId: "cozinha",
    attributes: { brightness: 100 },
    online: true,
    lastUpdated: new Date().toISOString(),
    platform: "tuya",
  },
  {
    id: "switch-sala-1",
    name: "Tomada TV",
    type: DeviceType.SWITCH,
    state: "on",
    roomId: "sala",
    attributes: {},
    online: true,
    lastUpdated: new Date().toISOString(),
    platform: "tuya",
  },
  {
    id: "switch-quarto-1",
    name: "Ventilador",
    type: DeviceType.FAN,
    state: "off",
    roomId: "quarto",
    attributes: {},
    online: true,
    lastUpdated: new Date().toISOString(),
    platform: "tuya",
  },
  {
    id: "climate-sala-1",
    name: "Ar Condicionado",
    type: DeviceType.CLIMATE,
    state: "on",
    roomId: "sala",
    attributes: { temperature: 23 },
    online: true,
    lastUpdated: new Date().toISOString(),
    platform: "tuya",
  },
  {
    id: "sensor-sala-1",
    name: "Sensor Temperatura",
    type: DeviceType.SENSOR,
    state: "on",
    roomId: "sala",
    attributes: { temperature: 24.5, humidity: 62 },
    online: true,
    lastUpdated: new Date().toISOString(),
    platform: "tuya",
  },
  {
    id: "camera-entrada-1",
    name: "Câmera Entrada",
    type: DeviceType.CAMERA,
    state: "on",
    roomId: "entrada",
    attributes: {},
    online: true,
    lastUpdated: new Date().toISOString(),
    platform: "tuya",
  },
  {
    id: "cover-sala-1",
    name: "Cortina Sala",
    type: DeviceType.COVER,
    state: "on",
    roomId: "sala",
    attributes: { position: 75 },
    online: true,
    lastUpdated: new Date().toISOString(),
    platform: "tuya",
  },
  {
    id: "light-escritorio-1",
    name: "Luz Escritório",
    type: DeviceType.LIGHT,
    state: "on",
    roomId: "escritorio",
    attributes: { brightness: 90 },
    online: true,
    lastUpdated: new Date().toISOString(),
    platform: "hue",
  },
  {
    id: "switch-escritorio-1",
    name: "Monitor",
    type: DeviceType.SWITCH,
    state: "on",
    roomId: "escritorio",
    attributes: {},
    online: true,
    lastUpdated: new Date().toISOString(),
    platform: "tuya",
  },
  {
    id: "sensor-quarto-1",
    name: "Sensor Quarto",
    type: DeviceType.SENSOR,
    state: "on",
    roomId: "quarto",
    attributes: { temperature: 22.1, humidity: 55 },
    online: true,
    lastUpdated: new Date().toISOString(),
    platform: "tuya",
  },
  {
    id: "light-banheiro-1",
    name: "Luz Banheiro",
    type: DeviceType.LIGHT,
    state: "off",
    roomId: "banheiro",
    attributes: { brightness: 100 },
    online: true,
    lastUpdated: new Date().toISOString(),
    platform: "tuya",
  },
  {
    id: "media-sala-1",
    name: "Smart TV",
    type: DeviceType.MEDIA_PLAYER,
    state: "off",
    roomId: "sala",
    attributes: { volume: 30 },
    online: true,
    lastUpdated: new Date().toISOString(),
    platform: "tuya",
  },
  {
    id: "switch-garagem-1",
    name: "Portão Garagem",
    type: DeviceType.SWITCH,
    state: "off",
    roomId: "garagem",
    attributes: {},
    online: true,
    lastUpdated: new Date().toISOString(),
    platform: "tuya",
  },
];

export const MOCK_ROOMS: Room[] = [
  {
    id: "sala",
    name: "Sala de Estar",
    icon: "sofa",
    order: 0,
    devices: [],
    deviceCounts: {},
  },
  {
    id: "quarto",
    name: "Quarto Principal",
    icon: "bed-double",
    order: 1,
    devices: [],
    deviceCounts: {},
  },
  {
    id: "cozinha",
    name: "Cozinha",
    icon: "cooking-pot",
    order: 2,
    devices: [],
    deviceCounts: {},
  },
  {
    id: "escritorio",
    name: "Escritório",
    icon: "monitor",
    order: 3,
    devices: [],
    deviceCounts: {},
  },
  {
    id: "banheiro",
    name: "Banheiro",
    icon: "bath",
    order: 4,
    devices: [],
    deviceCounts: {},
  },
  {
    id: "entrada",
    name: "Entrada",
    icon: "door-open",
    order: 5,
    devices: [],
    deviceCounts: {},
  },
  {
    id: "garagem",
    name: "Garagem",
    icon: "car",
    order: 6,
    devices: [],
    deviceCounts: {},
  },
];
